USE QLGiaoVienThamGiaDeTai
GO

--Q1. 
select HOTEN, LUONG
from GIAOVIEN
where PHAI = N'Nữ';

--Q2
select HOTEN,LUONG*1.1 as N'Lương khi tăng 10%' from GIAOVIEN;

--Q3
select G.MAGV
from GIAOVIEN G JOIN BOMON B ON G.MABM = B.MABM
where (G.HOTEN LIKE N'Nguyễn%' AND G.LUONG > 2000)
   OR (B.TRUONGBM = G.MAGV AND YEAR(B.NGAYNHANCHUC) > 1995);

--Q4
select G.HOTEN 
from GIAOVIEN G join BOMON B on G.MABM = B.MABM
where (B.MAKHOA = 'CNTT');

--Q5
select B.TENBM, B.MAKHOA, G.HOTEN AS TRUONGBM, G.LUONG, G.PHAI, G.NGAYSINH, G.DIACHI, B.NGAYNHANCHUC
from GIAOVIEN G join BOMON B on B.TRUONGBM = G.MAGV;

--Q6
select G.MAGV, G.HOTEN, G.LUONG, G.PHAI, G.NGAYSINH, G.DIACHI, B.TENBM, B.MAKHOA
from GIAOVIEN G join BOMON B on G.MABM = B.MABM;

--Q7
select D.MADT, D.TENDT, D.GVCNDT, G.HOTEN
from GIAOVIEN G join DETAI D on D.GVCNDT = G.MAGV;

--Q8
select K.MAKHOA, K.TENKHOA, G.HOTEN AS TRUONGKHOA, G.PHAI, G.NGAYSINH, G.DIACHI
from KHOA K join GIAOVIEN G on G.MAGV = K.TRUONGKHOA;

--Q9
select G.HOTEN 
from GIAOVIEN G join THAMGIADT D on G.MAGV = D.MAGV
where D.MADT = '006' and G.MABM = 'VS';

--Q10 Thành phố => ĐHQG do ko có dự án cấp Thành phố
SELECT D.MADT, C.TENCD, G.HOTEN AS GVCNDT, G.NGAYSINH, G.DIACHI
FROM DETAI D 
	JOIN GIAOVIEN G ON D.GVCNDT = G.MAGV
	JOIN CHUDE C ON D.MACD = C.MACD
WHERE D.CAPQL = N'ĐHQG';

--Q11
SELECT HOTEN FROM GIAOVIEN
WHERE (GVQLCM = '007');

--Q12:  Thay Nguyễn Thanh Tùng thành Nguyễn An Trung do ko có GV tên Nguyễn Thanh Tùng
SELECT G1.HOTEN, G2.HOTEN AS GVQLCM
FROM GIAOVIEN G1 JOIN GIAOVIEN G2 ON G1.GVQLCM = G2.MAGV
WHERE G2.HOTEN = N'Nguyễn An Trung';

--Q13
SELECT G.HOTEN AS TRUONGBM, B.TENBM
FROM GIAOVIEN G JOIN BOMON B ON G.MABM = B.MABM
WHERE B.MABM = 'HTTT';

--Q14
SELECT G.HOTEN AS NGUOIQL, D.TENDT
FROM DETAI D
	JOIN GIAOVIEN G ON G.MAGV = D.GVCNDT
	JOIN CHUDE CD ON D.MACD = CD.MACD
WHERE CD.TENCD = N'Quản lý giáo dục';

--Q15 
SELECT CV.TENCV, DT.TENDT, CV.NGAYBD
FROM DETAI DT JOIN CONGVIEC CV ON DT.MADT = CV.MADT
WHERE (CV.NGAYBD BETWEEN '03/01/2008' AND '03/31/2008') AND (DT.TENDT LIKE N'HTTT%');

--Q16
SELECT G1.HOTEN, G2.HOTEN AS GVQLCM
FROM GIAOVIEN G1 JOIN GIAOVIEN G2 ON G1.GVQLCM = G2.MAGV;

--Q17
SELECT TENCV, NGAYBD FROM CONGVIEC
WHERE NGAYBD BETWEEN '01/01/2007' AND '08/01/2007';

--Q18
SELECT G1.HOTEN, G1.MABM
FROM GIAOVIEN G1 JOIN GIAOVIEN G2 ON G1.MABM = G2.MABM
WHERE G2.HOTEN = N'Trần Trà Hương';

--Q19
SELECT GV.HOTEN, BM.TENBM, DT.TENDT
FROM GIAOVIEN GV
	JOIN DETAI DT ON GV.MAGV = DT.GVCNDT
	JOIN BOMON BM ON GV.MAGV = BM.TRUONGBM;

--Q20
SELECT GV.HOTEN, BM.TENBM, K.TENKHOA
FROM GIAOVIEN GV
	JOIN KHOA K ON GV.MAGV = K.TRUONGKHOA
	JOIN BOMON BM ON GV.MAGV = BM.TRUONGBM;

--Q21
SELECT GV.HOTEN AS TRUONGBM, BM.TENBM, DT.TENDT
FROM GIAOVIEN GV
	JOIN DETAI DT ON GV.MAGV = DT.GVCNDT
	JOIN BOMON BM ON GV.MAGV = BM.TRUONGBM;

--Q23
SELECT GV.HOTEN
FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV
WHERE GV.MABM = 'HTTT' OR TG.MADT = '001';

--Q24
SELECT G1.HOTEN, G1.MABM
FROM GIAOVIEN G1 JOIN GIAOVIEN G2 ON G1.MABM = G2.MABM
WHERE G2.MAGV = '002';

--Q25
SELECT GV.HOTEN AS TRUONGBM, BM.TENBM
FROM GIAOVIEN GV JOIN BOMON BM ON GV.MAGV = BM.TRUONGBM;

--Q26 
SELECT HOTEN, LUONG
FROM GIAOVIEN;