use QLGiaoVienThamGiaDeTai;
go

--Q58
SELECT DISTINCT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS (SELECT MACD FROM CHUDE
EXCEPT 
SELECT DT.MACD FROM THAMGIADT TG, DETAI DT WHERE TG.MAGV = GV.MAGV AND TG.MADT = DT.MADT)
GO

--Q59
SELECT DISTINCT DT.TENDT
FROM DETAI DT ON DT.MADT = TGDT.MADT
WHERE NOT EXISTS (SELECT GV.MAGV
			   FROM GIAOVIEN GV WHERE GV.MABM ='HTTT'
			   EXCEPT
			   SELECT DISTINCT GV.MAGV
			   FROM GIAOVIEN GV JOIN THAMGIADT TGDT ON GV.MAGV = TGDT.MAGV 
			   WHERE DT.MADT = TGDT.MADT AND GV.MABM ='HTTT' )
GO

--Q60
SELECT DT.TENDT
FROM DETAI DT
WHERE DT.MADT IN (
SELECT TG.MADT
			FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM
						JOIN THAMGIADT TG ON TG.MAGV = GV.MAGV
			WHERE BM.TENBM = N'HỆ THỐNG THÔNG TIN'
			GROUP BY TG.MADT
			HAVING COUNT(DISTINCT TG.MAGV) = (
SELECT COUNT(GV.MAGV)
				FROM GIAOVIEN GV JOIN BOMON BM ON GV.MABM = BM.MABM					
				WHERE BM.TENBM = N'HỆ THỐNG THÔNG TIN'))
GO

--Q61
SELECT DISTINCT GV.*
FROM THAMGIADT TGDT1 JOIN GIAOVIEN GV ON GV.MAGV = TGDT1.MAGV
WHERE NOT EXISTS (
	SELECT *
	FROM DETAI DT
	WHERE DT.MACD = 'QLGD' AND NOT EXISTS (
		SELECT *
		FROM THAMGIADT TGDT2
		WHERE TGDT2.MADT = DT.MADT AND TGDT2.MAGV = TGDT1.MAGV
	)
)

--Q62
SELECT DISTINCT GV1.HOTEN
FROM THAMGIADT TG1 JOIN GIAOVIEN GV1 ON TG1.MAGV = GV1.MAGV
WHERE NOT EXISTS (
	(SELECT MADT FROM DETAI DT1 WHERE DT1.MADT IN 
		(
			SELECT DT2.MADT
			FROM THAMGIADT DT2 JOIN GIAOVIEN GV2 ON DT2.MAGV = GV2.MAGV
			WHERE GV2.HOTEN = 'Trần Trà Hương'
		))
	EXCEPT 
	(SELECT MADT FROM THAMGIADT TG3 WHERE TG3.MAGV = TG1.MAGV)
)

--Q63
SELECT DISTINCT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS (    	  SELECT GV.MAGV
				  FROM GIAOVIEN GV JOIN BOMON BM ON BM.MABM=GV.MABM 
				  AND BM.TENBM =N'Hoá Hữu Cơ'
				  EXCEPT
				  SELECT DISTINCT GV.MAGV
				  FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV  
				                                     JOIN BOMON BM ON BM.MABM=GV.MABM 
				  WHERE DT.MADT = TG.MADT AND BM.TENBM = N'Hoá Hữu Cơ' )
GO

--Q64
SELECT DISTINCT GV1.HOTEN
FROM THAMGIADT TG1 JOIN GIAOVIEN GV1 ON TG1.MAGV = GV1.MAGV
WHERE NOT EXISTS (
	(SELECT MADT FROM DETAI DT1 WHERE DT1.MADT = '006')
	EXCEPT 
	(SELECT MADT FROM THAMGIADT TG3 WHERE TG3.MAGV = TG1.MAGV)
)
GO

--Q65
SELECT GV.*
FROM THAMGIADT TGDT1 JOIN GIAOVIEN GV ON GV.MAGV = TGDT1.MAGV
WHERE NOT EXISTS (
	SELECT *
	FROM DETAI DT JOIN CHUDE CD ON DT.MACD = CD.MACD
	WHERE CD.TENCD = N'Ứng dụng công nghệ' AND NOT EXISTS (
		SELECT *
		FROM THAMGIADT TGDT2
		WHERE TGDT2.MADT = DT.MADT AND TGDT2.MAGV = TGDT1.MAGV
	)
)
GO

--Q66
SELECT DISTINCT GV.*
FROM THAMGIADT TGDT1 JOIN GIAOVIEN GV ON GV.MAGV = TGDT1.MAGV
WHERE NOT EXISTS (
	SELECT *
	FROM DETAI DT JOIN GIAOVIEN GV ON DT.GVCNDT = GV.MAGV
	WHERE GV.HOTEN = N'Trần Hà Hương' AND NOT EXISTS (
		SELECT *
		FROM THAMGIADT TGDT2
		WHERE TGDT2.MADT = DT.MADT AND TGDT2.MAGV = TGDT1.MAGV
	)
)
GO

--Q67
SELECT DISTINCT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS (
	SELECT GV.MAGV
	FROM GIAOVIEN GV JOIN BOMON BM ON BM.MABM=GV.MABM 
		AND BM.MAKHOA =N'CNTT'
	EXCEPT
	SELECT DISTINCT GV.MAGV
	FROM GIAOVIEN GV JOIN THAMGIADT TG ON GV.MAGV = TG.MAGV  
		JOIN BOMON BM ON BM.MABM=GV.MABM 
	WHERE DT.MADT = TG.MADT AND BM.MAKHOA = N'CNTT' )
GO

--Q68